@extends('layouts.app', ['class' => 'g-sidenav-show bg-gray-100'])

@section('content')
@include('layouts.navbars.auth.topnav', ['title' => 'Report Details'])

<div class="container-fluid py-4">
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <div class="row">
                        <div class="col-6 d-flex align-items-center">
                            <h6>{{ $report->name }}</h6>
                        </div>
                        <div class="col-6 text-end">
                            <div class="btn-group" role="group">
                                <a href="{{ route('reports.index') }}" class="btn btn-secondary btn-sm">
                                    <i class="fas fa-arrow-left"></i> Back
                                </a>
                                @if($report->file_path)
                                <a href="{{ route('reports.download', $report) }}" class="btn btn-success btn-sm">
                                    <i class="fas fa-download"></i> Download
                                </a>
                                @endif
                                <a href="{{ route('reports.export', $report) }}?format=pdf" class="btn btn-danger btn-sm">
                                    <i class="fas fa-file-pdf"></i> Export PDF
                                </a>
                                <a href="{{ route('reports.export', $report) }}?format=excel" class="btn btn-info btn-sm">
                                    <i class="fas fa-file-excel"></i> Export Excel
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Type:</strong> {{ \App\Models\Report::getTypes()[$report->type] ?? $report->type }}</p>
                            <p><strong>Generated By:</strong> {{ $report->generatedBy->name }}</p>
                            <p><strong>Generated At:</strong> {{ $report->generated_at->format('M d, Y H:i:s') }}</p>
                        </div>
                        <div class="col-md-6">
                            @if(isset($report->data['period']))
                            <p><strong>Period:</strong> {{ $report->data['period']['start_date'] }} to {{ $report->data['period']['end_date'] }}</p>
                            @endif
                            @if($report->file_path)
                            <p><strong>File Size:</strong> {{ $report->file_size }}</p>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if(isset($report->data['summary']))
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>Summary</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        @foreach($report->data['summary'] as $key => $value)
                        <div class="col-md-3 col-sm-6 mb-3">
                            <div class="card">
                                <div class="card-body p-3">
                                    <div class="row">
                                        <div class="col-8">
                                            <div class="numbers">
                                                <p class="text-sm mb-0 text-uppercase font-weight-bold">{{ ucwords(str_replace('_', ' ', $key)) }}</p>
                                                <h5 class="font-weight-bolder">
                                                    @if(is_numeric($value))
                                                        @if(str_contains($key, 'total') || str_contains($key, 'sales') || str_contains($key, 'revenue') || str_contains($key, 'cost') || str_contains($key, 'profit'))
                                                            Rp {{ number_format($value, 0, ',', '.') }}
                                                        @elseif(str_contains($key, 'margin'))
                                                            {{ number_format($value, 2) }}%
                                                        @else
                                                            {{ number_format($value) }}
                                                        @endif
                                                    @else
                                                        {{ $value }}
                                                    @endif
                                                </h5>
                                            </div>
                                        </div>
                                        <div class="col-4 text-end">
                                            <div class="icon icon-shape bg-gradient-primary shadow-primary text-center rounded-circle">
                                                <i class="ni ni-chart-bar-32 text-lg opacity-10" aria-hidden="true"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif

    @if(isset($report->data['data']) && count($report->data['data']) > 0)
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-header pb-0">
                    <h6>Detailed Data</h6>
                </div>
                <div class="card-body px-0 pt-0 pb-2">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                                <tr>
                                    @foreach(array_keys((array) $report->data['data'][0]) as $header)
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        {{ ucwords(str_replace('_', ' ', $header)) }}
                                    </th>
                                    @endforeach
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($report->data['data'] as $row)
                                <tr>
                                    @foreach((array) $row as $key => $value)
                                    <td class="align-middle">
                                        @if(is_numeric($value))
                                            @if(str_contains($key, 'total') || str_contains($key, 'sales') || str_contains($key, 'revenue') || str_contains($key, 'cost') || str_contains($key, 'profit') || str_contains($key, 'price'))
                                                Rp {{ number_format($value, 0, ',', '.') }}
                                            @elseif(str_contains($key, 'margin'))
                                                {{ number_format($value, 2) }}%
                                            @else
                                                {{ number_format($value) }}
                                            @endif
                                        @elseif(is_object($value) && isset($value->name))
                                            {{ $value->name }}
                                        @else
                                            {{ $value }}
                                        @endif
                                    </td>
                                    @endforeach
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif

    @if(empty($report->data['data']))
    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-body text-center py-5">
                    <i class="fas fa-chart-bar fa-3x text-muted mb-3"></i>
                    <h5 class="text-muted">No Data Available</h5>
                    <p class="text-muted">There is no data available for the selected period and report type.</p>
                </div>
            </div>
        </div>
    </div>
    @endif
</div>
@endsection

