<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Support for the offline-capable cashier:
 * - client_uuid: generated by the browser for every sale, so a retried request
 *   (lost response, offline queue) can never create the same sale twice.
 * - is_offline: the sale was made without a connection and synced later.
 * - needs_review: syncing found a problem (stock went negative, price changed) for an admin to check.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('transactions', function (Blueprint $table) {
            $table->uuid('client_uuid')->nullable()->unique()->after('transaction_code');
            $table->boolean('is_offline')->default(false)->after('status');
            $table->boolean('needs_review')->default(false)->after('is_offline');
        });
    }

    public function down(): void
    {
        Schema::table('transactions', function (Blueprint $table) {
            $table->dropUnique(['client_uuid']);
            $table->dropColumn(['client_uuid', 'is_offline', 'needs_review']);
        });
    }
};
